# Original CraftPotionUtil.fromBukkit results for valid PotionData combinations.
AWKWARD.false.false=minecraft:awkward
FIRE_RESISTANCE.false.false=minecraft:fire_resistance
FIRE_RESISTANCE.true.false=minecraft:long_fire_resistance
INSTANT_DAMAGE.false.false=minecraft:harming
INSTANT_DAMAGE.false.true=minecraft:strong_harming
INSTANT_HEAL.false.false=minecraft:healing
INSTANT_HEAL.false.true=minecraft:strong_healing
INVISIBILITY.false.false=minecraft:invisibility
INVISIBILITY.true.false=minecraft:long_invisibility
JUMP.false.false=minecraft:leaping
JUMP.false.true=minecraft:strong_leaping
JUMP.true.false=minecraft:long_leaping
LUCK.false.false=minecraft:luck
MUNDANE.false.false=minecraft:mundane
NIGHT_VISION.false.false=minecraft:night_vision
NIGHT_VISION.true.false=minecraft:long_night_vision
POISON.false.false=minecraft:poison
POISON.false.true=minecraft:strong_poison
POISON.true.false=minecraft:long_poison
REGEN.false.false=minecraft:regeneration
REGEN.false.true=minecraft:strong_regeneration
REGEN.true.false=minecraft:long_regeneration
SLOWNESS.false.false=minecraft:slowness
SLOWNESS.false.true=minecraft:strong_slowness
SLOWNESS.true.false=minecraft:long_slowness
SLOW_FALLING.false.false=minecraft:slow_falling
SLOW_FALLING.true.false=minecraft:long_slow_falling
SPEED.false.false=minecraft:swiftness
SPEED.false.true=minecraft:strong_swiftness
SPEED.true.false=minecraft:long_swiftness
STRENGTH.false.false=minecraft:strength
STRENGTH.false.true=minecraft:strong_strength
STRENGTH.true.false=minecraft:long_strength
THICK.false.false=minecraft:thick
TURTLE_MASTER.false.false=minecraft:turtle_master
TURTLE_MASTER.false.true=minecraft:strong_turtle_master
TURTLE_MASTER.true.false=minecraft:long_turtle_master
UNCRAFTABLE.false.false=minecraft:empty
WATER.false.false=minecraft:water
WATER_BREATHING.false.false=minecraft:water_breathing
WATER_BREATHING.true.false=minecraft:long_water_breathing
WEAKNESS.false.false=minecraft:weakness
WEAKNESS.true.false=minecraft:long_weakness
